### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by mdozmorov** [mdozmorov/genome_runner#105]
When selecting all Roadmap data, or both ENCODE and Roadmap, the error message:
    413 Request Entity Too Large
    nginx/1.4.6 (Ubuntu)

Can we catch this with a message "Too many genomic features selected. Please, split your analysis into smaller runs by selecting smaller sets of genomic features for each run."

**Comment by lkscara** [comment]
See http://cnedelcu.blogspot.com/2013/09/nginx-error-413-request-entity-too-large.html
Add:
 client_max_body_size 10M;
to the nginx config file
