### ISSUE TITLE
RSID conversion not working for custom 'text' uploaded background

### ISSUE THREAD

**Issue by lkscara** [mdozmorov/genome_runner#65]

**Comment by mdozmorov** [comment]
Custom SNP set:
1) Upload rsIDs - works
2) Paste rsIDs - works
3) Upload BED - works
4) Paste BED - works

Custom background:
1) Upload rsIDs - works
2) Paste rsIDs - breaks "ERROR No valid FOIs to supplied"
3) Upload BED - works
4) Paste BED - works
