### ISSUE TITLE
DNAse imputed extra files

### ISSUE THREAD

**Issue by mdozmorov** [mdozmorov/genome_runner#75]
Now, DNase imputed narrowPeak and gappedPeak contain under Group/EID two files. E.g.
E033-DNase_imputed.bed.gz
E033-DNase_imputed_gappedPeak.bed.gz
[cellType]-[factor_factor]-[source] # use gPk instead of gappedPeak
E033-DNase_gPk-imputed

They are the same, except the latter has 4th column with gPk. We should keep the 'E033-DNase_imputed_gappedPeak.bed.gz' name, as it is unique identifier.

**Comment by lkscara** [comment]
Download and use E033-DNase_imputed.bed.gz but rename to E033-DNase_gPk-imputed.bed.gz
