### ISSUE TITLE
Calculating p-values

### ISSUE THREAD

**Issue by mdozmorov** [mdozmorov/genome_runner#83]
We need to calculate p-values using Fisher's exact test only, using strategu in https://github.com/mdozmorov/R.genomerunner/blob/master/genomeRunner_file_formatting_functions2.R

Data for testing:

infile <- "/Users/mikhail/Documents/Work/GenomeRunner/Paper-Similarity/data_Farh/ENCODE_Dgf/detailed.txt"
cases when OR equal to 0
   foi_obs n_fois bkg_obs n_bkg
1        0    155     203  7735
2        0     46     938  7735
3        0     47     938  7735
4        0    195     189  7735
5        0    175     161  7735
6        0     46     816  7735
7        0    195     177  7735
8        0    197     151  7735
9        0    234     176  7735
10       0     43     712  7735
11       0    195     200  7735
12       0    195     224  7735
13       0    173     187  7735
14       0     46     754  7735
15       0     46     776  7735
16       0     47     752  7735
17       0    141     218  7735
18       0     46     773  7735
19       0    195     180  7735
20       0     46     652  7735
21       0    234     194  7735
22       0    175     194  7735
23       0    195     179  7735

"/Users/mikhail/Documents/Work//GenomeRunner/gwas2bed/autoimmune/R.GR.autoimmune/data.gr/Roadmap_chromStates18/detailed.txt"
cases when OR equal to infinity. With "*" also have significant p-value, thus not overlap 1.
   foi_obs n_fois bkg_obs n_bkg
1        1    696       1  7735
2        1    261       1  7735
3        1     63       1  7735 *
4        1    110       1  7735 *
5        1    696       1  7735
6        1    370       1  7735
7        1    264       1  7735
8        2    696       2  7735 *
9        1    430       1  7735
10       1    696       1  7735
11       1    175       1  7735 *
12       2    787       2  7735 *
13       1    339       1  7735
14       2    696       2  7735 *
15      46     46    3850  7735 *
16       1    696       1  7735
17      46     46    4717  7735 *
18      46     46    4109  7735 *
19       2    787       2  7735 *
20       1    192       1  7735 *
21      46     46    4165  7735 *
22       1    787       1  7735
23       1    175       1  7735 *

**Comment by lkscara** [comment]
Fixed in  b8c6c622187c6eac0acd4509de1f41f3f035a4b6
